name: auto create unescape-gml file

on:
  push:
    paths:
      - 'dirs/**.gml'

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python and Run
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
          architecture: x64
      - run: python numetric_char_str.py
      - name: Run a multi-line script
        run: |
          git config user.name ${NAME}
          git config user.email ${EMAIL}
          git remote set-url origin https://${NAME}:${{ secrets.USER_GITHUB }}@github.com/${NAME}/${REPO}
          git add .
          git commit -m "create unescape gml file"
          git pull
          git push origin master
        env:
          NAME: 'NAME'
          EMAIL: 'EMAIL'
          REPO: 'REPO'
